export const ERROR_CODES = {
    NOT_FOUND: "NOT_FOUND",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
    DATABASE_ERROR: "DATABASE_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    SERVER_ERROR: "SERVER_ERROR"
};